services:
  backend:
    build:
      context: ./backend
    container_name: smart-leads-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: smart-leads-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_healthy
